### ISSUE TITLE
set prompt to off by default

### ISSUE THREAD

**Issue by bendichter** [jurasofish/sphinx-toggleprompt#11]
Thanks for making this! Would it be possible to add an option to set the prompt to be off by default?

**Comment by jurasofish** [comment]
Great idea, cheers, I've done an initial implementation in #14. 
You can preview it here https://sphinx-toggleprompt.readthedocs.io/en/default_on_off/

One issue is that it flickers on page load, because hiding/showing is done after the page is displayed. It might be possible to have it hide things before the page is rendered but that's outside my current skillset.

What do you reckon?

**Comment by bendichter** [comment]
@jurasofish this looks great! I don't see any flicker on my machine. @h-mayorquin, what do you think?

**Comment by h-mayorquin** [comment]
I would like to second @bendichter here and say: thanks a lot for working on this! both the project and the PR : D!

I tested this locally and it works for me.

As for the flicker, on my side, it is there sometimes and sometimes it is not. In fact, I was not aware of this but it seems that most of our documentation has some flicker here and there (at least on my browser).

**Comment by bendichter** [comment]
@jurasofish do you think you could push a release with this new feature?

**Comment by jurasofish** [comment]
all sorted, V0.2.0 published
